name: Greetings on Merge and Push

on:
  pull_request:
    branches:
      - '*'

jobs:
  hello_mr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Say Hello to MR
        run: echo "Hello, MR!"