name: Greetings on Merge and Push

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  hello_master:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Say Hello to Master
        run: echo "Hello, master!"

  hello_branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref != 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Say Hello to Branch
        run: echo "Hello, branch!"